
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SOCKET_RESPONSESOCKET`
-- ----------------------------
DROP TABLE IF EXISTS `SOCKET_RESPONSESOCKET`;
CREATE TABLE `SOCKET_RESPONSESOCKET` (
 		`RESPONSESOCKET_ID` varchar(100) NOT NULL,
		`CONTENT` varchar(255) DEFAULT NULL COMMENT '报文',
		`STATE` varchar(255) DEFAULT NULL COMMENT '状态',
		`CREATETIME` varchar(32) DEFAULT NULL COMMENT '创建时间',
  		PRIMARY KEY (`RESPONSESOCKET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
