
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SOCKET_STARTSOCKETPORT`
-- ----------------------------
DROP TABLE IF EXISTS `SOCKET_STARTSOCKETPORT`;
CREATE TABLE `SOCKET_STARTSOCKETPORT` (
 		`STARTSOCKETPORT_ID` varchar(100) NOT NULL,
		`FROMTEXT` varchar(255) DEFAULT NULL COMMENT '传入的报文',
		`STATE` varchar(1) DEFAULT NULL COMMENT '状态',
		`SENDTIME` varchar(32) DEFAULT NULL COMMENT '发送时间',
  		PRIMARY KEY (`STARTSOCKETPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
