
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SOCKET_TOOTHTERCOMP`
-- ----------------------------
DROP TABLE IF EXISTS `SOCKET_TOOTHTERCOMP`;
CREATE TABLE `SOCKET_TOOTHTERCOMP` (
 		`TOOTHTERCOMP_ID` varchar(100) NOT NULL,
		`TOTEXT` varchar(255) DEFAULT NULL COMMENT '解析后发送出去的报文',
		`STATE` varchar(255) DEFAULT NULL COMMENT '状态',
		`SENDTIME` varchar(32) DEFAULT NULL COMMENT '发送时间',
  		PRIMARY KEY (`TOOTHTERCOMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
