
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SOCKET_PORTSOCKETPORT`
-- ----------------------------
DROP TABLE IF EXISTS `SOCKET_PORTSOCKETPORT`;
CREATE TABLE `SOCKET_PORTSOCKETPORT` (
 		`SOCKETPORT_ID` varchar(100) NOT NULL,
		`PORT` varchar(255) DEFAULT NULL COMMENT '端口',
		`STATE` varchar(255) DEFAULT NULL COMMENT '状态',
		`CREATTIME` varchar(32) DEFAULT NULL COMMENT '创建时间',
  		PRIMARY KEY (`SOCKETPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
