
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SOCKET_REQUESTSOCKET`
-- ----------------------------
DROP TABLE IF EXISTS `SOCKET_REQUESTSOCKET`;
CREATE TABLE `SOCKET_REQUESTSOCKET` (
 		`REQUESTSOCKET_ID` varchar(100) NOT NULL,
		`CONTENT` varchar(255) DEFAULT NULL COMMENT '报文内容',
		`STATE` varchar(255) DEFAULT NULL COMMENT '状态',
		`CRATETIME` varchar(32) DEFAULT NULL COMMENT '创建时间',
  		PRIMARY KEY (`REQUESTSOCKET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
