
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SPSM_NAVBARTYPE`
-- ----------------------------
DROP TABLE IF EXISTS `SPSM_NAVBARTYPE`;
CREATE TABLE `SPSM_NAVBARTYPE` (
 		`NAVBARTYPE_ID` varchar(100) NOT NULL,
		`NAVBARNAME` varchar(255) DEFAULT NULL COMMENT '导航名称',
		`DATABASEID` varchar(255) DEFAULT NULL COMMENT '库类别',
  		PRIMARY KEY (`NAVBARTYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
