
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SPSM_SPIDER`
-- ----------------------------
DROP TABLE IF EXISTS `SPSM_SPIDER`;
CREATE TABLE `SPSM_SPIDER` (
 		`SPIDER_ID` varchar(100) NOT NULL,
		`TITLE` varchar(255) DEFAULT NULL COMMENT '标题',
		`AUTHOR` varchar(255) DEFAULT NULL COMMENT '作者',
		`ABSTRACT` varchar(255) DEFAULT NULL COMMENT '摘要',
		`CONTENT` varchar(255) DEFAULT NULL COMMENT '内容',
		`TYPE` int(11) NOT NULL COMMENT '类型',
		`PUBLISH_TIME` varchar(32) DEFAULT NULL COMMENT '发布时间',
		`CREATE_TIME` varchar(32) DEFAULT NULL COMMENT '爬取时间',
		`KEYWORDS` varchar(255) DEFAULT NULL COMMENT '关键字',
  		PRIMARY KEY (`SPIDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
