
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SPSM_ACHIEVEMENT`
-- ----------------------------
DROP TABLE IF EXISTS `SPSM_ACHIEVEMENT`;
CREATE TABLE `SPSM_ACHIEVEMENT` (
 		`ACHIEVEMENT_ID` varchar(100) NOT NULL,
		`TITLE` varchar(255) DEFAULT NULL COMMENT '标题',
		`COMPLETE_ORG` varchar(255) DEFAULT NULL COMMENT '完成单位',
		`COMPLETE_PER` varchar(255) DEFAULT NULL COMMENT '完成人',
		`ENCOURAGEMENT_CLASS` varchar(255) DEFAULT NULL COMMENT '奖励类型',
		`ENCOURAGEMENT_GRADE` varchar(255) DEFAULT NULL COMMENT '奖励等级',
		`ENCOURAGEMENT_DATE` varchar(255) DEFAULT NULL COMMENT '获奖时间',
		`ENCOURAGEMENT_LEVEL` varchar(255) DEFAULT NULL COMMENT '获奖级别',
		`DESCRIPTION` varchar(255) DEFAULT NULL COMMENT '描述',
		`ORGANIZATION_NAME` varchar(255) DEFAULT NULL COMMENT '联系单位名称',
		`ORGANIZATION_ADDRESS` varchar(255) DEFAULT NULL COMMENT '联系单位地址',
		`ORGANIZATION_POSTCODE` varchar(255) DEFAULT NULL COMMENT '联系单位邮编',
		`ORGANIZATION_PHONE` varchar(255) DEFAULT NULL COMMENT '联系单位电话',
		`ORGANIZATION_LINKMAN` varchar(255) DEFAULT NULL COMMENT '联系人',
		`SOURCE` varchar(255) DEFAULT NULL COMMENT '奖励来源',
		`DATA_PUBLIC_NAME` varchar(255) DEFAULT NULL COMMENT '奖励发布单位',
		`DATA_PUBLIC_DATE` varchar(255) DEFAULT NULL COMMENT '获奖时间',
		`KEYWORDS` varchar(255) DEFAULT NULL COMMENT '关键字',
		`IDENTIFY_DATE` varchar(255) DEFAULT NULL COMMENT '认证时间',
		`IDENTIFY_ORG` varchar(255) DEFAULT NULL COMMENT '认证单位',
		`REGISTRATION_MARK` varchar(255) DEFAULT NULL COMMENT '注册标志',
		`PUBLIC_ORGANIZATION` varchar(255) DEFAULT NULL COMMENT '公共机构',
		`PUBLIC_DATE` varchar(255) DEFAULT NULL COMMENT '发布时间',
		`CREATE_TIME` varchar(32) DEFAULT NULL COMMENT '创建时间',
		`HIT` int(11) NOT NULL COMMENT '点击量',
  		PRIMARY KEY (`ACHIEVEMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
