
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `SPSM_PERSON`
-- ----------------------------
DROP TABLE IF EXISTS `SPSM_PERSON`;
CREATE TABLE `SPSM_PERSON` (
 		`PERSON_ID` varchar(100) NOT NULL,
		`NAME` varchar(255) DEFAULT NULL COMMENT '育种专家姓名',
		`ORGANIZATION` varchar(255) DEFAULT NULL COMMENT '所在单位',
		`SEX` varchar(255) DEFAULT NULL COMMENT '性别',
		`SCHOOL_RECORD` varchar(255) DEFAULT NULL COMMENT '学历',
		`POSITION` varchar(255) DEFAULT NULL COMMENT '职务',
		`PROJECT` varchar(255) DEFAULT NULL COMMENT '领域',
		`EMAIL` varchar(255) DEFAULT NULL COMMENT '邮箱',
		`PHONE` varchar(255) DEFAULT NULL COMMENT '电话',
		`DESCRIPTION` varchar(255) DEFAULT NULL COMMENT '个人信息',
		`KEYWORDS` varchar(255) DEFAULT NULL COMMENT '关键词',
		`CREATE_TIME` varchar(255) DEFAULT NULL COMMENT '创建时间',
		`HIT` varchar(255) DEFAULT NULL COMMENT '点击次数',
  		PRIMARY KEY (`PERSON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
