package com.sample
import java.util.Date;
import com.ronxuntech.component.socket.ServerInHandler.*;
import com.ronxuntech.component.socket.util.IsoChannelMessageFactory;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.LinkedHashMap;

rule "190000"
no-loop true
    when
        m : Message(m.getProcessCode.equals("190000"),myMessage:message)
    then
        IsoChannelMessageFactory parseMessage=new IsoChannelMessageFactory(m.getPath());//8583配置xm文件
        LinkedHashMap<String, Object> map = m.getBitmap();//解析包
   
    	LinkedHashMap<String,Object> returnMap=parseMessage.packNew(map,"190000.xml", m);
    	
        update(m);
end

